server:
  port: 8020
#应用名称 nacos会将该名称当做服务名称
spring:
  application:
    name: order-service
  cloud:
    nacos:
      server-addr: 127.0.0.1:8848
      #登录nacos的用户名和密码，不配置的话时默认的nacos、nacos
      discovery:
        username: nacos
        password: nacos
        #命名空间的作用：在服务管理服务列表处体现，可以划分服务的分组，默认的时public
        #一般开发都会有多套环境，如果多套环境公用一个nacos，那么配置中心和注册中心都会发生冲突，所以需要用namespace隔离开
        namespace: public